import TopBar from "@/components/TopBar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import MenuProvider from "@/lib/providers/MenuProvider";

const general = localFont({
  src: [
    {
      path: "../public/fonts/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-Medium.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-general",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ipsum.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${general.variable} antialiased`}>
        <MenuProvider>
          <TopBar />

          {/* ScrollSmoother container */}
          <div id="smooth-wrapper">
            <div id="smooth-content">{children}</div>
          </div>
        </MenuProvider>
      </body>
    </html>
  );
}
