import TopBar from "@/components/TopBar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const general = localFont({
  src: [
    {
      path: "../public/fonts/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-Medium.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-general",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ipsum.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${general.variable} antialiased bg-[#292929]`}>
        <TopBar />

        {/* ScrollSmoother container */}
        <div id="smooth-wrapper">
          <div id="smooth-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
